# -*- coding: utf-8 -*-

# 모의 레시피 데이터 (Zero Waste AI Refrigerator Dashboard)
RECIPES = [
    {
        "name": "두부 야채 볶음 (Eco-Tofu Stir-fry)",
        "ingredients": ["두부", "대파", "파프리카", "양파"],
        "style": "한식",
        "avoidance": ["비건 선호"],  # 이 레시피는 비건 선호에 적합 (기피 재료 없음)
        "importance": "영양 밸런스",
        "spicy": "백김치 수준",
        "main_category": "채소·두부 중심",
        "concept": "건강한 다이어트식",
        "method": "볶음·구이",
        "cooking_time": 15,
        "difficulty": "쉬움",
        "zero_waste_tip": "남은 자투리 야채들을 모두 털어 넣기 좋은 환경 친화적 레시피입니다. 파프리카 꼬지나 양파 뿌리 부분 외에는 버릴 것이 없어요!",
        "calories": 210,
        "description": "달콤짭조름한 간장 소스에 부드러운 두부와 아삭한 야채를 볶아낸 건강식입니다."
    },
    {
        "name": "매콤 소고기 볶음 (Spicy Beef Stir-fry)",
        "ingredients": ["소고기", "양파", "대파", "마늘"],
        "style": "한식",
        "avoidance": ["없음"],
        "importance": "맛의 깊이",
        "spicy": "신라면 수준",
        "main_category": "육류 중심",
        "concept": "든든한 보양식",
        "method": "볶음·구이",
        "cooking_time": 20,
        "difficulty": "보통",
        "zero_waste_tip": "질긴 소고기 부위도 얇게 썰어 대파와 양파의 단맛을 활용하면 조미료 사용을 줄이고 음식물 쓰레기도 예방할 수 있습니다.",
        "calories": 420,
        "description": "신라면 수준의 매콤한 소스로 입맛을 돋우는 소고기 대파 볶음 요리입니다."
    },
    {
        "name": "갈릭 크림 파스타 (Garlic Cream Pasta)",
        "ingredients": ["파스타면", "베이컨", "마늘", "우유", "치즈"],
        "style": "양식",
        "avoidance": ["없음"],  # 유제품 포함되어 있음
        "importance": "비주얼",
        "spicy": "백김치 수준",
        "main_category": "탄수화물류 면·밥",
        "concept": "홈파티 정취 요리",
        "method": "에어프라이어·오븐",  # 볶음 후 오븐베이크 가능
        "cooking_time": 20,
        "difficulty": "보통",
        "zero_waste_tip": "유통기한이 임박한 우유와 슬라이스 치즈를 대량 소진하기에 최적인 크림 파스타 요리법입니다.",
        "calories": 580,
        "description": "마늘향이 가득하고 고소한 크림 베이스에 면을 버무린 홈파티 인기 파스타입니다."
    },
    {
        "name": "불닭 볶음 우동 (Super Spicy Fried Udon)",
        "ingredients": ["우동면", "닭고기", "양배추", "양파"],
        "style": "퓨전",
        "avoidance": ["없음"],
        "importance": "맛의 깊이",
        "spicy": "불닭 수준",
        "main_category": "탄수화물류 면·밥",
        "concept": "든든한 보양식",
        "method": "볶음·구이",
        "cooking_time": 15,
        "difficulty": "쉬움",
        "zero_waste_tip": "냉장고 한구석에 숨겨져 있던 자투리 양배추와 닭고기 조각들을 매콤한 양념으로 맛있게 부활시키는 레시피입니다.",
        "calories": 490,
        "description": "매운 음식을 사랑하는 분들을 위한 화끈한 불닭 소스 베이스의 볶음 우동입니다."
    },
    {
        "name": "해물 토마토 스튜 (Seafood Tomato Stew)",
        "ingredients": ["새우", "오징어", "토마토", "양파", "마늘"],
        "style": "양식",
        "avoidance": ["갑각류"],  # 새우 기피자는 피해야 함
        "importance": "영양 밸런스",
        "spicy": "신라면 수준",
        "main_category": "해산물 중심",
        "concept": "홈파티 정취 요리",
        "method": "국물·탕·찌개",
        "cooking_time": 25,
        "difficulty": "어려움",
        "zero_waste_tip": "물러져서 그냥 먹기 힘든 토마토를 스튜 베이스로 끓여내면 훌륭한 소스가 되며, 남은 해산물 믹스를 모두 소비하기 좋습니다.",
        "calories": 310,
        "description": "토마토 소스의 깊은 산미와 신선한 해산물이 어우러져 시원한 국물 맛을 내는 해물 스튜입니다."
    },
    {
        "name": "견과류 멸치 볶음 (Nutty Anchovy Stir-fry)",
        "ingredients": ["멸치", "아몬드", "호두", "마늘"],
        "style": "한식",
        "avoidance": ["견과류"],  # 견과류 알레르기 있으면 피해야 함
        "importance": "영양 밸런스",
        "spicy": "백김치 수준",
        "main_category": "해산물 중심",
        "concept": "건강한 다이어트식",
        "method": "볶음·구이",
        "cooking_time": 10,
        "difficulty": "쉬움",
        "zero_waste_tip": "눅눅해진 견과류를 마른 팬에 살짝 볶아 수분을 날리고 바삭한 멸치와 볶아내면 훌륭한 밥반찬이자 고단백 밑반찬이 됩니다.",
        "calories": 180,
        "description": "고소한 견과류와 짭조름한 멸치를 물엿에 졸여내 바삭한 식감을 자랑하는 볶음입니다."
    },
    {
        "name": "초간단 계란 간장밥 (Simple Egg Soy Rice)",
        "ingredients": ["밥", "계란", "참기름", "김가루"],
        "style": "한식",
        "avoidance": ["비건 선호"],  # 락토-오보 비건 가능
        "importance": "조리 시간(초간단)",
        "spicy": "백김치 수준",
        "main_category": "탄수화물류 면·밥",
        "concept": "건강한 다이어트식",
        "method": "볶음·구이",
        "cooking_time": 5,
        "difficulty": "쉬움",
        "zero_waste_tip": "냉동실에 얼려둔 찬밥을 해동하여 계란 하나로 탄소 배출을 최소화하며 한 끼를 때울 수 있는 친환경 초간단 레시피입니다.",
        "calories": 350,
        "description": "시간이 없을 때 5분 만에 완성하는 마성의 간장 계란 참기름 비빔밥입니다."
    },
    {
        "name": "연어 샐러드 (Fresh Salmon Salad)",
        "ingredients": ["연어", "양상추", "방울토마토", "레몬"],
        "style": "일식",
        "avoidance": ["없음"],
        "importance": "조리 시간(초간단)",
        "spicy": "백김치 수준",
        "main_category": "해산물 중심",
        "concept": "건강한 다이어트식",
        "method": "샐러드·무침",
        "cooking_time": 8,
        "difficulty": "쉬움",
        "zero_waste_tip": "불 없이 조리하여 가스/전기 에너지를 사용하지 않는 저탄소 친환경 요리입니다. 자투리 채소를 바닥에 깔아 샐러드로 소진해 보세요.",
        "calories": 260,
        "description": "신선한 훈제연어와 아삭한 샐러드 채소에 상큼한 소스를 곁들인 가벼운 요리입니다."
    },
    {
        "name": "버섯 전골 (Eco-Mushroom Hot Pot)",
        "ingredients": ["느타리버섯", "팽이버섯", "두부", "대파", "배추"],
        "style": "한식",
        "avoidance": ["비건 선호"],
        "importance": "맛의 깊이",
        "spicy": "신라면 수준",
        "main_category": "채소·두부 중심",
        "concept": "든든한 보양식",
        "method": "국물·탕·찌개",
        "cooking_time": 25,
        "difficulty": "보통",
        "zero_waste_tip": "시들어가는 알배기 배추와 버섯 밑동을 잘 씻어 육수를 내면 깊은 감칠맛을 내며, 채식 위주의 조리로 탄소 배출을 80% 이상 줄일 수 있습니다.",
        "calories": 190,
        "description": "다양한 자투리 버섯과 두부를 배추와 함께 맑게 끓여낸 건강하고 든든한 전골 요리입니다."
    },
    {
        "name": "꿔바로우식 버섯 탕수 (Sweet and Sour Mushrooms)",
        "ingredients": ["표고버섯", "전분가루", "당근", "오이"],
        "style": "중식",
        "avoidance": ["비건 선호"],
        "importance": "비주얼",
        "spicy": "백김치 수준",
        "main_category": "채소·두부 중심",
        "concept": "홈파티 정취 요리",
        "method": "볶음·구이",
        "cooking_time": 30,
        "difficulty": "어려움",
        "zero_waste_tip": "고기 대신 표고버섯을 메인으로 사용하여 육류 소비를 줄이고 온실가스를 감축하며, 새콤달콤한 소스에 당근과 오이 자투리를 활용합니다.",
        "calories": 320,
        "description": "쫄깃한 표고버섯에 전분 옷을 입혀 튀겨내고, 새콤달콤한 소스를 부어 꿔바로우 식감을 낸 탕수 요리입니다."
    },
    {
        "name": "상큼 과일 요거트볼 (Fruity Yogurt Bowl)",
        "ingredients": ["요거트", "사과", "바나나", "꿀"],
        "style": "퓨전",
        "avoidance": ["없음"],  # 요거트(유제품)가 포함되어 있음
        "importance": "조리 시간(초간단)",
        "spicy": "백김치 수준",
        "main_category": "채소·두부 중심",
        "concept": "건강한 다이어트식",
        "method": "샐러드·무침",
        "cooking_time": 5,
        "difficulty": "쉬움",
        "zero_waste_tip": "갈변된 사과나 너무 익어 껍질이 까매진 바나나를 작게 썰어 요거트에 섞으면, 달콤함은 배가 되고 음식물 쓰레기는 제로가 됩니다!",
        "is_dessert": True,
        "calories": 150,
        "description": "상큼하고 달콤한 과일들과 유산균 가득한 요거트가 만나 입안을 깔끔하게 마무리해 주는 디저트 볼입니다."
    },
    {
        "name": "상큼 민트 레몬에이드 (Mint Lemonade Dessert)",
        "ingredients": ["레몬", "탄산수", "설탕", "민트잎"],
        "style": "양식",
        "avoidance": ["비건 선호"],
        "importance": "조리 시간(초간단)",
        "spicy": "백김치 수준",
        "main_category": "채소·두부 중심",
        "concept": "홈파티 정취 요리",
        "method": "샐러드·무침",
        "cooking_time": 5,
        "difficulty": "쉬움",
        "zero_waste_tip": "남아서 굳어가는 레몬 슬라이스나 베란다 텃밭의 허브를 소진하여 깔끔하고 청량한 디저트 음료를 완성합니다.",
        "is_dessert": True,
        "calories": 80,
        "description": "식사 후 상큼한 과즙과 톡 쏘는 탄산으로 입안을 산뜻하게 채워주는 상쾌한 에이드 음료입니다."
    }
]
